# This is a basic workflow to help you get started with Actions

name: Welcome Workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      TENANT:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, Welcome to World of Resuable Workflows!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: display vars from parent workflow
        run: |
          echo "ReusableWorkflow: ${{ inputs.VERSION }}"
          echo "ReusableWorkflow: ${{ inputs.TENANT }}"
